branches:
  only:
    - master

language: go

script-anchors:
  - &script-linux-coverage
    - cd $TRAVIS_BUILD_DIR
    - make
    - make coverage
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7

matrix:
  include:
    - os: linux
      dist: bionic
      go:
        - 1.13.x
      git:
        depth: 3
      addons:
        apt:
          packages:
            - build-essential
      env:
        - MATRIX_EVAL="GO111MODULE=on"
      script: *script-linux-coverage

before_install:
  - eval "${MATRIX_EVAL}"
