name: Unittest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get packages
      run: DEBIAN_FRONTEND=noninteractive sudo apt install -y build-essential

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: make build

    - name: Test
      run: make coverage

    - name: Report
      run: bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7
